### ISSUE TITLE
Raster input plugin throws error if JAI/ImageIO not installed 

### ISSUE THREAD

**Issue by chrisbennight** [locationtech/geowave#332]
Initially reported on gitter linked to gist here:
https://gist.github.com/kitplummer/b574edab3ac3f3c4ba57

```
[bennight@cacti data]$ geowave-ingest --localingest -b /data/natural_earth/ -i $INSTANCE -n geowave -p $GEOWAVE_PASS -u $GEOWAVE_USER -z $ZOOKEEPERS
Apr 11, 2015 4:54:49 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'GeoServerResourceLoader', but ApplicationContext is unset.
Apr 11, 2015 4:54:49 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'GeoServerResourceLoader', but ApplicationContext is unset.
Apr 11, 2015 4:54:49 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'GeoServerResourceLoader', but ApplicationContext is unset.
Apr 11, 2015 4:54:49 PM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'GeoServerResourceLoader', but ApplicationContext is unset.
Apr 11, 2015 4:54:50 PM org.geotools.factory.FactoryRegistry scanForPlugins
WARNING: Can't load a service for category "GridFormatFactorySpi". Cause is "ServiceConfigurationError: org.geotools.coverage.grid.io.GridFormatFactorySpi: Provider org.geotools.gce.imagemosaic.ImageMosaicFormatFactory could not be instantiated".
java.util.ServiceConfigurationError: org.geotools.coverage.grid.io.GridFormatFactorySpi: Provider org.geotools.gce.imagemosaic.ImageMosaicFormatFactory could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.geotools.factory.FactoryRegistry.register(FactoryRegistry.java:826)
        at org.geotools.factory.FactoryRegistry.scanForPlugins(FactoryRegistry.java:772)
        at org.geotools.factory.FactoryRegistry.scanForPlugins(FactoryRegistry.java:750)
        at org.geotools.coverage.grid.io.GridFormatFinder.scanForPlugins(GridFormatFinder.java:122)
        at org.geotools.coverage.grid.io.GridFormatFinder.getAvailableFormats(GridFormatFinder.java:85)
        at org.geotools.coverage.grid.io.GridFormatFinder.findFormats(GridFormatFinder.java:178)
        at org.geotools.coverage.grid.io.GridFormatFinder.findFormat(GridFormatFinder.java:241)
        at org.geotools.coverage.grid.io.GridFormatFinder.findFormat(GridFormatFinder.java:216)
        at mil.nga.giat.geowave.types.geotools.raster.GeoToolsRasterDataStoreIngestPlugin.supportsFile(GeoToolsRasterDataStoreIngestPlugin.java:61)
        at mil.nga.giat.geowave.ingest.local.LocalPluginFileVisitor$PluginVisitor.supportsFile(LocalPluginFileVisitor.java:74)
        at mil.nga.giat.geowave.ingest.local.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:125)
        at mil.nga.giat.geowave.ingest.local.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:30)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at mil.nga.giat.geowave.ingest.local.AbstractLocalFileDriver.processInput(AbstractLocalFileDriver.java:60)
        at mil.nga.giat.geowave.ingest.local.LocalFileIngestDriver.runInternal(LocalFileIngestDriver.java:114)
        at mil.nga.giat.geowave.ingest.AbstractCommandLineDriver.run(AbstractCommandLineDriver.java:72)
        at mil.nga.giat.geowave.ingest.IngestMain.main(IngestMain.java:51)
Caused by: java.util.ServiceConfigurationError: javax.imageio.spi.ImageInputStreamSpi: Provider com.sun.media.imageioimpl.stream.ChannelImageInputStreamSpi could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:210)
        at javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:138)
        at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:159)
        at it.geosolutions.imageio.utilities.ImageIOUtilities.replaceProvider(ImageIOUtilities.java:452)
        at org.geotools.gce.imagemosaic.ImageMosaicFormatFactory.replaceTIFF(ImageMosaicFormatFactory.java:343)
        at org.geotools.gce.imagemosaic.ImageMosaicFormatFactory.<clinit>(ImageMosaicFormatFactory.java:61)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: vendorName == null!
        at javax.imageio.spi.IIOServiceProvider.<init>(IIOServiceProvider.java:76)
        at javax.imageio.spi.ImageInputStreamSpi.<init>(ImageInputStreamSpi.java:90)
        at com.sun.media.imageioimpl.stream.ChannelImageInputStreamSpi.<init>(ChannelImageInputStreamSpi.java:63)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 34 more

Apr 11, 2015 4:54:50 PM org.geotools.factory.FactoryRegistry scanForPlugins
WARNING: Can't load a service for category "GridFormatFactorySpi". Cause is "ServiceConfigurationError: org.geotools.coverage.grid.io.GridFormatFactorySpi: Provider org.geotools.gce.imagemosaic.ImageMosaicFormatFactory could not be instantiated".
java.util.ServiceConfigurationError: org.geotools.coverage.grid.io.GridFormatFactorySpi: Provider org.geotools.gce.imagemosaic.ImageMosaicFormatFactory could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at org.geotools.factory.FactoryRegistry.register(FactoryRegistry.java:826)
        at org.geotools.factory.FactoryRegistry.scanForPlugins(FactoryRegistry.java:772)
        at org.geotools.factory.FactoryRegistry.scanForPlugins(FactoryRegistry.java:750)
        at org.geotools.coverage.grid.io.GridFormatFinder.scanForPlugins(GridFormatFinder.java:122)
        at org.geotools.coverage.grid.io.GridFormatFinder.getAvailableFormats(GridFormatFinder.java:85)
        at org.geotools.coverage.grid.io.GridFormatFinder.findFormats(GridFormatFinder.java:178)
        at org.geotools.coverage.grid.io.GridFormatFinder.findFormat(GridFormatFinder.java:241)
        at org.geotools.coverage.grid.io.GridFormatFinder.findFormat(GridFormatFinder.java:216)
        at mil.nga.giat.geowave.types.geotools.raster.GeoToolsRasterDataStoreIngestPlugin.toGeoWaveData(GeoToolsRasterDataStoreIngestPlugin.java:74)
        at mil.nga.giat.geowave.types.geotools.raster.GeoToolsRasterDataStoreIngestPlugin.toGeoWaveData(GeoToolsRasterDataStoreIngestPlugin.java:35)
        at mil.nga.giat.geowave.ingest.local.LocalFileIngestDriver.processFile(LocalFileIngestDriver.java:146)
        at mil.nga.giat.geowave.ingest.local.LocalFileIngestDriver.processFile(LocalFileIngestDriver.java:33)
        at mil.nga.giat.geowave.ingest.local.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:126)
        at mil.nga.giat.geowave.ingest.local.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:30)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at mil.nga.giat.geowave.ingest.local.AbstractLocalFileDriver.processInput(AbstractLocalFileDriver.java:60)
        at mil.nga.giat.geowave.ingest.local.LocalFileIngestDriver.runInternal(LocalFileIngestDriver.java:114)
        at mil.nga.giat.geowave.ingest.AbstractCommandLineDriver.run(AbstractCommandLineDriver.java:72)
        at mil.nga.giat.geowave.ingest.IngestMain.main(IngestMain.java:51)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.geotools.gce.imagemosaic.ImageMosaicFormatFactory
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 22 more

Exception in thread "main" java.lang.UnsupportedOperationException: Trying to get a reader from an unknown format.
        at org.geotools.coverage.grid.io.UnknownFormat.getReader(UnknownFormat.java:62)
        at mil.nga.giat.geowave.types.geotools.raster.GeoToolsRasterDataStoreIngestPlugin.toGeoWaveData(GeoToolsRasterDataStoreIngestPlugin.java:75)
        at mil.nga.giat.geowave.types.geotools.raster.GeoToolsRasterDataStoreIngestPlugin.toGeoWaveData(GeoToolsRasterDataStoreIngestPlugin.java:35)
        at mil.nga.giat.geowave.ingest.local.LocalFileIngestDriver.processFile(LocalFileIngestDriver.java:146)
        at mil.nga.giat.geowave.ingest.local.LocalFileIngestDriver.processFile(LocalFileIngestDriver.java:33)
        at mil.nga.giat.geowave.ingest.local.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:126)
        at mil.nga.giat.geowave.ingest.local.LocalPluginFileVisitor.visitFile(LocalPluginFileVisitor.java:30)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at mil.nga.giat.geowave.ingest.local.AbstractLocalFileDriver.processInput(AbstractLocalFileDriver.java:60)
        at mil.nga.giat.geowave.ingest.local.LocalFileIngestDriver.runInternal(LocalFileIngestDriver.java:114)
        at mil.nga.giat.geowave.ingest.AbstractCommandLineDriver.run(AbstractCommandLineDriver.java:72)
        at mil.nga.giat.geowave.ingest.IngestMain.main(IngestMain.java:51)
[bennight@cacti data]$
```

**Comment by SDeathLeaDer** [comment]
@chrisbennight  i have the same bug :(

**Comment by rfecher** [comment]
to clarify the raster format plugin requires JAI and cannot be used if JAI is not installed.  However, we should be able to support vector ingest or any other format even if the raster format cannot be used and that is the spirit of this ticket.

**Comment by rfecher** [comment]
this is related to #333

**Comment by datasedai** [comment]
Might have been fixed with @rfecher latest commit

**Comment by LeandroCR7** [comment]
wich one of the two jai library is required because the Documentation says that Geotools use jai-image-io to read and write raster files, but use jai for raster support and is optional, why is required when you are working with raster images if the Documentation say that is optional. I even check the jar files includes in Geotools 17.1 and there is a jai_core and others files of the jai-image-io library inside, why are those files there if they don't use it.
#
 4. Optional – Java Advanced Imaging is used by GeoTools for raster support. If you install JAI 1.1.3 performance will be improved:
Both a JDK and JRE installer are available:

    jai-1_1_3-lib-windows-i586-jdk.exe
    jai-1_1_3-lib-windows-i586-jre.exe

5. Optional – ImageIO Is used to read and write raster files. GeoTools uses version 1_1 of the ImageIO library:
Both a JDK and JRE installer are available:

    jai_imageio-1_1-lib-windows-i586-jdk.exe
    jai_imageio-1_1-lib-windows-i586-jre.exe
#
I download and install this one jai_imageio-1_1-lib-windows-i586-jre.exe and the same error continues showing up.

I need a solution please.

**Comment by rfecher** [comment]
we leverage geotools for many of the raster operations, and assuming its in reference to trying to use the `geotools-raster` input format for ingest into GeoWave it is going to use JAI and JAI-ImageIO.  I think the missing piece in your case is to also install JAI.

Here is the latest documentation from GeoTools.  It calls these extensions optional but if you're working with raster data I *think* the recommendation is still to make sure you install them, although I know there has also been a decent amount of work towards jai-ext (java-based extensions):
http://docs.geotools.org/latest/userguide/build/install/jdk.html#java-extensions-optional

Regarding the libraries being included with geotools, this is true, but there are also native libraries associated with JAI and ImageIO (dlls for windows) that end up being dropped in a subdirectory of your jdk or jre (I believe it goes in  ./lib/ext).

Hopefully that helps but if you still have issues maybe sharing a stack trace would provide insights.

**Comment by LeandroCR7** [comment]
rfecher thanks for your answer, but I still having the same error, I´m using Netbeans 8 with jdk 1.8_60 and both lib successfully installed jai_imageio-1_1-lib-windows-i586-jre.exe and jai-1_1_3-lib-windows-i586-jdk.exe. I create a Java Application project without using Maven because I hate it, so I don´t use it. And when I try this:

#
List<Parameter<?>> list = new ArrayList<>();
             list.add(new Parameter<>("image", File.class, "Image",
             "GeoTiff or World+Image to display as basemap",
             new KVP(Parameter.EXT, "tif", Parameter.EXT, "jpg")));

             JParameterListWizard wizard = new JParameterListWizard("Image Lab",
             "Fill in the following layers", list);
             int finish = wizard.showModalDialog();

             if (finish != JWizard.FINISH) {
             System.exit(0);
             }
             File rasterFile = (File) wizard.getConnectionParameters().get("image");
             AbstractGridFormat format = GridFormatFinder.findFormat(rasterFile);
             //this is a bit hacky but does make more geotiffs work
             Hints hints = new Hints();
             if (format instanceof GeoTiffFormat) {
             hints = new Hints(Hints.FORCE_LONGITUDE_FIRST_AXIS_ORDER, Boolean.TRUE);
             }

             GridCoverage2DReader reader = format.getReader(rasterFile, hints);

             // Initially display the raster in greyscale using the
             // data from the first image band
             Style rasterStyle = createGreyscaleStyle(1);
             Layer rasterLayer = new GridReaderLayer(reader, rasterStyle);
            
            // Create a map content and add our shapefile to it
            MapContent map = new MapContent();
            layers.stream().forEach((obj) -> {
                map.addLayer(obj);
            });

            map.addLayer(rasterLayer);
#

I get this error in Netbeans output console:

# 
jun 26, 2017 10:37:07 AM org.geotools.factory.FactoryRegistry scanForPlugins
ADVERTENCIA: Error en la inicialización de un servicio de categoría "GridFormatFactorySpi". La causa es "ServiceConfigurationError: org.geotools.coverage.grid.io.GridFormatFactorySpi: Provider org.geotools.gce.imagemosaic.ImageMosaicFormatFactory could not be instantiated".
java.util.ServiceConfigurationError: org.geotools.coverage.grid.io.GridFormatFactorySpi: Provider org.geotools.gce.imagemosaic.ImageMosaicFormatFactory could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.geotools.factory.FactoryRegistry.register(FactoryRegistry.java:826)
	at org.geotools.factory.FactoryRegistry.scanForPlugins(FactoryRegistry.java:772)
	at org.geotools.factory.FactoryRegistry.scanForPlugins(FactoryRegistry.java:750)
	at org.geotools.coverage.grid.io.GridFormatFinder.scanForPlugins(GridFormatFinder.java:122)
	at org.geotools.coverage.grid.io.GridFormatFinder.getAvailableFormats(GridFormatFinder.java:85)
	at org.geotools.coverage.grid.io.GridFormatFinder.findFormats(GridFormatFinder.java:178)
	at org.geotools.coverage.grid.io.GridFormatFinder.findFormat(GridFormatFinder.java:236)
	at org.geotools.coverage.grid.io.GridFormatFinder.findFormat(GridFormatFinder.java:216)
#

I hope you can help me now. Greetings to all and thanks for the help.

The Geotools lib have a lot of work, like Java programmer I can say that is amazing what it does, but the interfaces management is bad, horrible, I can´t understand why if I add a button to the toolbar to increase the funcionality of my project, the whole lib goes crazy, completely crazy, The LayerTable duplicate all the Layers, and it start to function with a lot of issues, I even change a icon of the toolbar button and the same thing It goes crazy (and it is a lot of work to do that). I think that the developers should work in the interface managment because right now is a nightmare. I don't like to be forced using their interfaces because it destroy the desing work and use a JLayerdPane to the whole window desing (talking about the JMapFrame), why you do that?, you are limitating the lib's funcionality. I can help the lib's creators with the interfaces, to organize the views and make easier the work with it.

**Comment by rfecher** [comment]
I'd encourage you to discuss issues you have with geotools on the geotools-dev mailing list.  [Here's ](https://sourceforge.net/p/geoserver/mailman/geoserver-users/thread/CAJaHrDxWJADkasUbQ%2BHnALV%3D735XiQzjNVj1fbM7QYtEHZxYFw%40mail.gmail.com/#msg35480413)a related thread on the geoserver-users list.

**Comment by LeandroCR7** [comment]
No I´m using just that one jdk 1.8_60. I even create a virtual machine with VirtualBox because I have a program that only work with jdk 1.7 I, so I can´t install jdk 1.8 or other in my computer because this program it´s part of my job. 

But installing JDK instead of JRE create both folders a jdk folder and a jre folder, so my question is: should I install both libs in each one of those two folder or just in jre folder? By default it is installed only in jre folder.

**Comment by LeandroCR7** [comment]
No, I tried with that idea, it did not work. So I still having the same problem, I can't display images with geotools. 

How you can see I'm using the code of the example of the documentation, I even download the same data of the example, and I'm using the images clouds.jpg and earthlights.jpg and nothing same bug all the times.

thanks anyway, I give up for today.

I created a virtual machine to install only jdk 1.8 as requested by the library. Download the two JAI libraries and install both. I've tried everything and nothing, I remove libs I put it back again and nothing still the same bug, so I give up.
